<?php

namespace Andrey\GalleryBundle\Repository;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * AlbumMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumMediaRepository extends SortableRepository
{
}
