andrey_gallery_homepage:
    path:     /
    defaults: { _controller: AndreyGalleryBundle:Default:index }

andrey_gallery_album_list:
    path:     /gallery/list.{_format}
    defaults: { _controller: andrey.gallery.controller.list:indexAction, _format: json }
    methods:  ["GET"]

andrey_gallery_album_get:
    path:     /gallery/album.{_format}
    defaults: { _controller: andrey.gallery.controller.album:indexAction, _format: json }
    methods:  ["GET"]
