imports:
    - { resource: entity_managers.yml }
    - { resource: controllers.yml }

services:
#    andrey_gallery.example:
#        class: Andrey\GalleryBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
