Andrey\GalleryBundle\Entity\Album:
    type: entity
    table: null
    repositoryClass: Andrey\GalleryBundle\Repository\AlbumRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
